#!groovy
pipeline {
    agent any
    tools {
        maven 'M3'
        }
    stages {
        stage('Maven Install'){
          steps {
            agent {
              script {
                docker {
                    image 'maven:3.5.0'
                    }
                  }
                }
              }
            }
        stage('Build') {
            steps {
                sh 'mvn --version'
                sh 'mvn clean install'
                echo 'Build Stage Successful'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                echo 'Test Stage Successful'
                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn deploy'
                echo 'Deployment Successful'
            }
        }
    }
    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}